/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Usuarios;
import DAO.connectDAO;

import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Alunos
 */
public class Cad_Usuarios extends javax.swing.JFrame {
    String operacaoAtivaGlobal ="Nenhum";

    /**
     * Creates new form Cad_Usuarios
     */
    public Cad_Usuarios() {
        initComponents();
       
    
    }
    
    public Cad_Usuarios(String operacaoAtiva){
        //Constructor
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        
        if(operacaoAtiva.equals(operacao)){
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField5.setVisible(true);
            jButton1.setText(operacaoAtivaGlobal + " BD");
            
                    
        }
        operacao = "Alterar";
        if(operacaoAtiva.equals(operacao)){
            jLabel2.setVisible(false);
            jLabel3.setVisible(true);
            jLabel1.setVisible(false);
            jLabel6.setVisible(false);
            
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(true);
            jTextField5.setVisible(false);
            jButton1.setText(operacaoAtivaGlobal + " BD");
                        
        }      
        
         operacao = "Excluir";
        if(operacaoAtiva.equals(operacao)){
            jLabel2.setVisible(false);
            jLabel3.setVisible(true);
            jLabel1.setVisible(false);
            jLabel6.setVisible(false);
            
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(true);
            jTextField5.setVisible(false);
            jButton1.setText(operacaoAtivaGlobal + " BD");
                        
        }  
    }
    
Usuarios usuarios_tela = new Usuarios();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero Agência");

        jLabel2.setText("Senha");

        jLabel3.setText("Id");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Usuários");

        jButton1.setText("Incluir DB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar Tela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero Conta");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField5.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField5.setText(Integer.toString(usuarios_tela.getNumero_agencia()));
        jTextField1.setText(Integer.toString(usuarios_tela.getNumero_conta()));
        jTextField2.setText( usuarios_tela.getSenha());
        jTextField3.setText(usuarios_tela.getId());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao))
          {
            Usuarios usuarios_tela = new Usuarios();
            usuarios_tela.setNumero_agencia(Integer.parseInt(jTextField5.getText()));
            usuarios_tela.setNumero_conta(Integer.parseInt(jTextField1.getText()));
            usuarios_tela.setSenha(jTextField2.getText());
            usuarios_tela.setId(jTextField3.getText());
        
         //Inserção no banco de dados
          connectDAO objcon = new connectDAO();
          objcon.connectDB();
          objcon.insereRegistroJFBD("USUARIOS", usuarios_tela.dadosSQLValues());
          }
        operacao = "Alteração";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
              
              Usuarios usuarios_tela = new Usuarios();
              usuarios_tela.setNumero_agencia(Integer.parseInt(jTextField5.getText()));
              usuarios_tela.setNumero_conta(Integer.parseInt(jTextField1.getText()));
              usuarios_tela.setSenha(jTextField2.getText());
              usuarios_tela.setId(jTextField3.getText());
              
              objcon.alteraRegistroJFBD("USUARIOS", usuarios_tela.alteraDadoSQLValues(), "ID = '" + jTextField3.getText() + "'");
                  
 
          }
          
          operacao = "Alterar";
          if (operacaoAtivaGlobal.equals(operacao))
          {
                Usuarios usuarios_tela = new Usuarios();
                connectDAO objcon = new connectDAO();
                usuarios_tela= objcon.pesquisaUsuarioJFBD("USUARIOS"," ID = '" + jTextField3.getText() + "'");
                jTextField5.setText(Integer.toString(usuarios_tela.getNumero_agencia()));
                jTextField1.setText(Integer.toString(usuarios_tela.getNumero_conta()));
                jTextField2.setText(usuarios_tela.getSenha());
                jTextField3.setText(usuarios_tela.getId());
                usuarios_tela.setId(jTextField3.getText());
             
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jLabel1.setVisible(true);
                jLabel6.setVisible(true);

                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                jTextField5.setVisible(true);
                jButton2.setVisible(false);
                jButton3.setVisible(false);
                jButton1.setText("Alterar");
                operacaoAtivaGlobal = "Alteração";
                
                }
          
          operacao = "Exclusão";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
              objcon.excluiRegistroJFBD("USUARIOS","ID = '" + jTextField3.getText()+ "'");
                 
                jTextField5.setText("");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                this.dispose();
 
          }
          
           operacao = "Excluir";
          if (operacaoAtivaGlobal.equals(operacao))
          {
                connectDAO objcon = new connectDAO();
                usuarios_tela = objcon.pesquisaUsuarioJFBD("USUARIOS","ID = '" + jTextField3.getText() + "'");
               
                jTextField5.setText(Integer.toString(usuarios_tela.getNumero_agencia()));
                jTextField1.setText(Integer.toString(usuarios_tela.getNumero_conta()));
                jTextField2.setText(usuarios_tela.getSenha());
                jTextField3.setText(usuarios_tela.getId());
                
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jLabel1.setVisible(true);
                jLabel6.setVisible(true);

                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                jTextField5.setVisible(true);
                jButton2.setVisible(false);
                jButton3.setVisible(false);
                
                 jTextField1.setEditable(false);
                jTextField2.setEditable(false);
                jTextField3.setEditable(false);
                jTextField5.setEditable(false);
                jButton2.setVisible(false);
                jButton3.setVisible(false);
                jButton1.setText("Excluir");
                operacaoAtivaGlobal = "Exclusão";
                
                }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
