/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Agencias;
import DAO.connectDAO;
/**
 *
 * @author Alunos
 */
public class Cad_Agencias extends javax.swing.JFrame {
    String operacaoAtivaGlobal ="Nenhum";

    /**
     * Creates new form Cad_Agencias
     */
    public Cad_Agencias() {
        initComponents();
    }

    
     public Cad_Agencias(String operacaoAtiva){
        //Constructor
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        
        if(operacaoAtiva.equals(operacao)){
            Txt_NumAgencia.setVisible(true);
            Txt_Nome.setVisible(true);
            Txt_Endereco.setVisible(true);
            Txt_Numero.setVisible(true);
            Txt_Complemento.setVisible(true);
            Txt_Bairro.setVisible(true);
            Txt_Cidade.setVisible(true);
            Txt_Uf.setVisible(true);
            Txt_Cep.setVisible(true);
            Txt_Telefone.setVisible(true);
            BtnCadastrar.setText(operacaoAtivaGlobal + " BD");
        }
        
         operacao = "Alterar";
        if(operacaoAtiva.equals(operacao)){
            jLabel2.setVisible(true);
            jLabel3.setVisible(false);
            jLabel10.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel12.setVisible(false);
            
            
            Txt_NumAgencia.setVisible(true);
            Txt_Nome.setVisible(false);
            Txt_Cep.setVisible(false);
            Txt_Endereco.setVisible(false);
            Txt_Numero.setVisible(false);
            Txt_Complemento.setVisible(false);
            Txt_Bairro.setVisible(false);
            Txt_Cidade.setVisible(false);
            Txt_Uf.setVisible(false);
            Txt_Telefone.setVisible(false);
            BtnCadastrar.setText(operacaoAtivaGlobal + " BD");
        }
        
         operacao = "Excluir";
        if(operacaoAtiva.equals(operacao)){
            jLabel2.setVisible(true);
            jLabel3.setVisible(false);
            jLabel10.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel12.setVisible(false);
            
            
            Txt_NumAgencia.setVisible(true);
            Txt_Nome.setVisible(false);
            Txt_Cep.setVisible(false);
            Txt_Endereco.setVisible(false);
            Txt_Numero.setVisible(false);
            Txt_Complemento.setVisible(false);
            Txt_Bairro.setVisible(false);
            Txt_Cidade.setVisible(false);
            Txt_Uf.setVisible(false);
            Txt_Telefone.setVisible(false);
            BtnCadastrar.setText(operacaoAtivaGlobal + " BD");
        }
    }
    
    Agencias agencia_tela = new Agencias();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Txt_Endereco = new javax.swing.JTextField();
        Txt_Nome = new javax.swing.JTextField();
        Txt_NumAgencia = new javax.swing.JTextField();
        Txt_Complemento = new javax.swing.JTextField();
        Txt_Cep = new javax.swing.JTextField();
        Txt_Cidade = new javax.swing.JTextField();
        Txt_Telefone = new javax.swing.JTextField();
        Txt_Bairro = new javax.swing.JTextField();
        Txt_Uf = new javax.swing.JTextField();
        BtnCadastrar = new javax.swing.JButton();
        BtnLimparTela = new javax.swing.JButton();
        BtnLer = new javax.swing.JButton();
        Txt_Numero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("AGÊNCIAS");

        jLabel2.setText("Número da Agência:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Endereço:");

        jLabel5.setText("Número:");

        jLabel6.setText("Complemento:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Cidade:");

        jLabel9.setText("UF:");

        jLabel10.setText("CEP:");

        jLabel12.setText("Telefone:");

        Txt_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EnderecoActionPerformed(evt);
            }
        });

        Txt_NumAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NumAgenciaActionPerformed(evt);
            }
        });

        Txt_Cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CepActionPerformed(evt);
            }
        });

        Txt_Uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_UfActionPerformed(evt);
            }
        });

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        BtnLimparTela.setText("Limpar Tela");
        BtnLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparTelaActionPerformed(evt);
            }
        });

        BtnLer.setText("Ler");
        BtnLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLerActionPerformed(evt);
            }
        });

        Txt_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_NumAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Endereco)
                            .addComponent(Txt_Complemento)
                            .addComponent(Txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(Txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(BtnCadastrar)
                                .addGap(222, 222, 222)
                                .addComponent(BtnLimparTela)))
                        .addGap(182, 182, 182)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnLer)
                    .addComponent(Txt_Uf, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(Txt_Bairro, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(Txt_Cep)
                    .addComponent(Txt_Numero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Txt_Telefone)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_NumAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Txt_Uf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar)
                    .addComponent(BtnLimparTela)
                    .addComponent(BtnLer))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_CepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CepActionPerformed

    private void Txt_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EnderecoActionPerformed

    private void Txt_UfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_UfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_UfActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao))
        {
              
              Agencias agencia_tela = new Agencias();
          
        
          agencia_tela.setNum_agencia(Integer.parseInt(Txt_NumAgencia.getText()));
          agencia_tela.setNome(Txt_Nome.getText());
          agencia_tela.setEndereco(Txt_Endereco.getText());
          agencia_tela.setNumero(Txt_Numero.getText());
          agencia_tela.setComplemento(Txt_Complemento.getText());
          agencia_tela.setBairro(Txt_Bairro.getText());
          agencia_tela.setCidade(Txt_Cidade.getText());
          agencia_tela.setUf(Txt_Uf.getText());
          agencia_tela.setCep(Txt_Cep.getText());
          agencia_tela.setTelefone(Txt_Telefone.getText());
          
           connectDAO objcon = new connectDAO();
          objcon.connectDB();
          objcon.insereRegistroJFBD("AGENCIAS", agencia_tela.dadosSQLValues());
          
          }
          
          operacao = "Alteração";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
              
              Agencias agencia_tela = new Agencias();
                agencia_tela.setNum_agencia(Integer.parseInt(Txt_NumAgencia.getText()));
                agencia_tela.setNome(Txt_Nome.getText());
                agencia_tela.setEndereco(Txt_Endereco.getText());
                agencia_tela.setNumero(Txt_Numero.getText());
                agencia_tela.setComplemento(Txt_Complemento.getText());
                agencia_tela.setBairro(Txt_Bairro.getText());
                agencia_tela.setCidade(Txt_Cidade.getText());
                agencia_tela.setUf(Txt_Uf.getText());
                agencia_tela.setCep(Txt_Cep.getText());
                agencia_tela.setTelefone(Txt_Telefone.getText());

                objcon.alteraRegistroJFBD("AGENCIAS", agencia_tela.alteraDadoSQLValues(), "NUM_AGE = '" + Txt_NumAgencia.getText()+ "'");
          }
          
           operacao = "Alterar";
          if (operacaoAtivaGlobal.equals(operacao))
          {
                connectDAO objcon = new connectDAO();
                agencia_tela = objcon.pesquisaAgenciasJFBD("AGENCIAS"," NUM_AGE = '" + Txt_NumAgencia.getText() + "'");

                Txt_NumAgencia.setText(Integer.toString(agencia_tela.getNum_agencia()));
                Txt_Nome.setText(agencia_tela.getNome());
                Txt_Endereco.setText(agencia_tela.getEndereco());
                Txt_Numero.setText(agencia_tela.getNumero());
                Txt_Complemento.setText(agencia_tela.getComplemento());
                Txt_Bairro.setText(agencia_tela.getBairro());
                Txt_Cidade.setText(agencia_tela.getCidade());
                Txt_Uf.setText(agencia_tela.getUf());
                Txt_Cep.setText(agencia_tela.getCep());
                Txt_Telefone.setText(agencia_tela.getTelefone());
                
                        
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel10.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel12.setVisible(true);
            
            Txt_NumAgencia.setVisible(true);
            Txt_Nome.setVisible(true);
            Txt_Cep.setVisible(true);
            Txt_Endereco.setVisible(true);
            Txt_Numero.setVisible(true);
            Txt_Complemento.setVisible(true);
            Txt_Bairro.setVisible(true);
            Txt_Cidade.setVisible(true);
            Txt_Uf.setVisible(true);
            Txt_Telefone.setVisible(true);
            BtnCadastrar.setText("Alterar");
            operacaoAtivaGlobal = "Alteração";
        }
          
          operacao = "Exclusão";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
              objcon.excluiRegistroJFBD("AGENCIAS", "NUM_AGE =" + Txt_NumAgencia.getText());
              
                Txt_NumAgencia.setText("");
                Txt_Nome.setText("");
                Txt_Endereco.setText("");
                Txt_Numero.setText("");
                Txt_Complemento.setText("");
                Txt_Bairro.setText("");
                Txt_Cidade.setText("");
                Txt_Uf.setText("");
                Txt_Cep.setText("");
                Txt_Telefone.setText("");
                this.dispose();
          }
          
          operacao = "Excluir";
          if (operacaoAtivaGlobal.equals(operacao))
          {
                connectDAO objcon = new connectDAO();
                agencia_tela = objcon.pesquisaAgenciasJFBD("AGENCIAS"," NUM_AGE = '" + Txt_NumAgencia.getText() + "'");

                Txt_NumAgencia.setText(Integer.toString(agencia_tela.getNum_agencia()));
                Txt_Nome.setText(agencia_tela.getNome());
                Txt_Endereco.setText(agencia_tela.getEndereco());
                Txt_Numero.setText(agencia_tela.getNumero());
                Txt_Complemento.setText(agencia_tela.getComplemento());
                Txt_Bairro.setText(agencia_tela.getBairro());
                Txt_Cidade.setText(agencia_tela.getCidade());
                Txt_Uf.setText(agencia_tela.getUf());
                Txt_Cep.setText(agencia_tela.getCep());
                Txt_Telefone.setText(agencia_tela.getTelefone());
                
                        
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel10.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel12.setVisible(true);
            
            Txt_NumAgencia.setVisible(true);
            Txt_Nome.setVisible(true);
            Txt_Cep.setVisible(true);
            Txt_Endereco.setVisible(true);
            Txt_Numero.setVisible(true);
            Txt_Complemento.setVisible(true);
            Txt_Bairro.setVisible(true);
            Txt_Cidade.setVisible(true);
            Txt_Uf.setVisible(true);
            Txt_Telefone.setVisible(true);
            
            Txt_NumAgencia.setEditable(false);
            Txt_Nome.setEditable(false);
            Txt_Cep.setEditable(false);
            Txt_Endereco.setEditable(false);
            Txt_Numero.setEditable(false);
            Txt_Complemento.setEditable(false);
            Txt_Bairro.setEditable(false);
            Txt_Cidade.setEditable(false);
            Txt_Uf.setEditable(false);
            Txt_Telefone.setEditable(false);
            BtnCadastrar.setText("Excluir");
            operacaoAtivaGlobal = "Exclusão";
        }
            
            
         // TODO add your handling code here:
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void Txt_NumAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NumAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NumAgenciaActionPerformed

    private void BtnLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparTelaActionPerformed

        Txt_NumAgencia.setText("");
        Txt_Nome.setText("");
        Txt_Endereco.setText("");
        Txt_Numero.setText("");
        Txt_Complemento.setText("");
        Txt_Bairro.setText("");
        Txt_Cidade.setText("");
        Txt_Uf.setText("");
        Txt_Cep.setText("");
        Txt_Telefone.setText("");
        
                    
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimparTelaActionPerformed

    private void BtnLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLerActionPerformed
        
        
        Txt_NumAgencia.setText(Integer.toString(agencia_tela.getNum_agencia()));
        Txt_Nome.setText(agencia_tela.getNome());
        Txt_Endereco.setText(agencia_tela.getEndereco());
        Txt_Numero.setText(agencia_tela.getNumero());
        Txt_Complemento.setText(agencia_tela.getComplemento());
        Txt_Bairro.setText(agencia_tela.getBairro());
        Txt_Cidade.setText(agencia_tela.getCidade());
        Txt_Uf.setText(agencia_tela.getUf());
        Txt_Cep.setText(agencia_tela.getCep());
        Txt_Telefone.setText(agencia_tela.getTelefone());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLerActionPerformed

    private void Txt_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Agencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnLer;
    private javax.swing.JButton BtnLimparTela;
    private javax.swing.JTextField Txt_Bairro;
    private javax.swing.JTextField Txt_Cep;
    private javax.swing.JTextField Txt_Cidade;
    private javax.swing.JTextField Txt_Complemento;
    private javax.swing.JTextField Txt_Endereco;
    private javax.swing.JTextField Txt_Nome;
    private javax.swing.JTextField Txt_NumAgencia;
    private javax.swing.JTextField Txt_Numero;
    private javax.swing.JTextField Txt_Telefone;
    private javax.swing.JTextField Txt_Uf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
