/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Clientes;
import DAO.connectDAO;
/**
 *
 * @author Alunos
 */
public class Cliente extends javax.swing.JFrame {
String operacaoAtivaGlobal ="Nenhum";
    
    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }
    
    public Cliente(String operacaoAtiva){
        //Constructor
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        
        if(operacaoAtiva.equals(operacao)){
            Txt_id.setVisible(true);
            Txt_telefone.setVisible(true);
            Txt_nome.setVisible(true);
            TxtDataNas.setVisible(true);
            Txt_CPF.setVisible(true);
            Txt_Cnpj.setVisible(true);
            txtcep.setVisible(true);
            Txt_endereco.setVisible(true);
            Txt_numero.setVisible(true);
            Txt_complemento.setVisible(true);
            Txt_bairro.setVisible(true);
            Txt_cidade.setVisible(true);
            Txt_uf.setVisible(true);
            Btn_Cadastrar.setText(operacaoAtivaGlobal + " BD");
            
                    
        }
        operacao = "Alterar";
        if(operacaoAtiva.equals(operacao)){
            jLabel14.setVisible(true);
            jLabel10.setVisible(false);
            jLabel1.setVisible(false);
            jlabel20.setVisible(false);
            Jlabel16.setVisible(false);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            jlabel20.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel7.setVisible(false);
            jLabel6.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            
            Txt_id.setVisible(true);
            Txt_telefone.setVisible(false);
            Txt_nome.setVisible(false);
            TxtDataNas.setVisible(false);
            Txt_CPF.setVisible(false);
            Txt_Cnpj.setVisible(false);
            txtcep.setVisible(false);
            Txt_endereco.setVisible(false);
            Txt_numero.setVisible(false);
            Txt_complemento.setVisible(false);
            Txt_bairro.setVisible(false);
            Txt_cidade.setVisible(false);
            Txt_uf.setVisible(false);
            Btn_Cadastrar.setText(operacaoAtivaGlobal + " BD");
        }
        
        operacao = "Excluir";
        if(operacaoAtiva.equals(operacao)){
            jLabel14.setVisible(true);
            jLabel10.setVisible(false);
            jLabel1.setVisible(false);
            jlabel20.setVisible(false);
            Jlabel16.setVisible(false);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            jlabel20.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel7.setVisible(false);
            jLabel6.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            
            Txt_id.setVisible(true);
            Txt_telefone.setVisible(false);
            Txt_nome.setVisible(false);
            TxtDataNas.setVisible(false);
            Txt_CPF.setVisible(false);
            Txt_Cnpj.setVisible(false);
            txtcep.setVisible(false);
            Txt_endereco.setVisible(false);
            Txt_numero.setVisible(false);
            Txt_complemento.setVisible(false);
            Txt_bairro.setVisible(false);
            Txt_cidade.setVisible(false);
            Txt_uf.setVisible(false);
            Btn_Cadastrar.setText("Pesquisar-Excluir");
        }
    }

    
    
    
    

    
    Clientes cliente_tela = new Clientes();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt_numero = new javax.swing.JTextField();
        Txt_nome = new javax.swing.JTextField();
        Txt_CPF = new javax.swing.JTextField();
        Txt_endereco = new javax.swing.JTextField();
        Btn_Cadastrar = new javax.swing.JButton();
        Btn_Ler = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Txt_complemento = new javax.swing.JTextField();
        Txt_uf = new javax.swing.JTextField();
        Txt_cidade = new javax.swing.JTextField();
        Txt_telefone = new javax.swing.JTextField();
        Txt_bairro = new javax.swing.JTextField();
        Btn_limparTela = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Txt_Cnpj = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Txt_id = new javax.swing.JTextField();
        txtcep = new javax.swing.JTextField();
        jlabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Jlabel16 = new javax.swing.JLabel();
        TxtDataNas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome :");

        jLabel2.setText("Endereço: ");

        jLabel3.setText("Número :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Clientes");

        Txt_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_numeroActionPerformed(evt);
            }
        });

        Txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nomeActionPerformed(evt);
            }
        });

        Txt_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CPFActionPerformed(evt);
            }
        });

        Txt_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_enderecoActionPerformed(evt);
            }
        });

        Btn_Cadastrar.setText("Cadastrar");
        Btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CadastrarActionPerformed(evt);
            }
        });

        Btn_Ler.setText("Ler");
        Btn_Ler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LerActionPerformed(evt);
            }
        });

        jLabel6.setText("Bairro:");

        jLabel7.setText("Complemento:");

        jLabel8.setText("Cidade:");

        jLabel9.setText("UF:");

        jLabel10.setText("Telefone:");

        Txt_complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_complementoActionPerformed(evt);
            }
        });

        Txt_uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ufActionPerformed(evt);
            }
        });

        Txt_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_cidadeActionPerformed(evt);
            }
        });

        Txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_telefoneActionPerformed(evt);
            }
        });

        Txt_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_bairroActionPerformed(evt);
            }
        });

        Btn_limparTela.setText("Limpar Tela");
        Btn_limparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limparTelaActionPerformed(evt);
            }
        });

        jLabel12.setText("CPF:");

        jLabel13.setText("CNPJ:");

        Txt_Cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CnpjActionPerformed(evt);
            }
        });

        jLabel14.setText("ID: ");

        Txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_idActionPerformed(evt);
            }
        });

        txtcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcepActionPerformed(evt);
            }
        });

        jlabel20.setText("CEP");

        Jlabel16.setText("Data de Nascimento:");

        TxtDataNas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDataNasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Btn_Cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_limparTela)
                .addGap(138, 138, 138)
                .addComponent(Btn_Ler)
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_uf, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(Txt_numero)
                            .addComponent(Txt_bairro)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1)
                                    .addComponent(jlabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_nome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtcep))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel12)
                                .addGap(37, 37, 37)
                                .addComponent(Txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(128, 128, 128))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Jlabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDataNas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27)
                        .addComponent(Txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel4)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel16)
                    .addComponent(TxtDataNas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Txt_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel20)
                    .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Txt_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_Ler)
                        .addComponent(Btn_limparTela)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_numeroActionPerformed

    private void Txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nomeActionPerformed

    private void Txt_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CPFActionPerformed

    private void Txt_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_enderecoActionPerformed

    private void Btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CadastrarActionPerformed
          // TODO add your handling code here:
          String operacao = "Incluir";
          if (operacaoAtivaGlobal.equals(operacao))
          {
            Clientes cliente_tela = new Clientes();              
            cliente_tela.setid_cli(Integer.parseInt(Txt_id.getText()));
            cliente_tela.setnome(Txt_nome.getText());
            cliente_tela.setdataNascimento(TxtDataNas.getText());
            cliente_tela.setcpf(Txt_CPF.getText());
            cliente_tela.setcnpj(Txt_Cnpj.getText());
            cliente_tela.setcep(txtcep.getText());
            cliente_tela.settelefone(Txt_telefone.getText());
            cliente_tela.setendereco(Txt_endereco.getText());
            cliente_tela.setnumero(Txt_numero.getText());
            cliente_tela.setcomplemento(Txt_complemento.getText());
            cliente_tela.setbairro(Txt_bairro.getText());
            cliente_tela.setcidade(Txt_cidade.getText());
            cliente_tela.setuf(Txt_uf.getText());
            


            //Inserção no banco de dados
            connectDAO objcon = new connectDAO();
            objcon.connectDB();
            objcon.insereRegistroJFBD("CLIENTES", cliente_tela.dadosSQLValues());
          }
          
          operacao = "Alteração";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
          
            Clientes cliente_tela = new Clientes();              
            cliente_tela.setid_cli(Integer.parseInt(Txt_id.getText()));
            cliente_tela.setnome(Txt_nome.getText());
            cliente_tela.setdataNascimento(TxtDataNas.getText());
            cliente_tela.setcpf(Txt_CPF.getText());
            cliente_tela.setcnpj(Txt_Cnpj.getText());
            cliente_tela.setcep(txtcep.getText());
            cliente_tela.settelefone(Txt_telefone.getText());
            cliente_tela.setendereco(Txt_endereco.getText());
            cliente_tela.setnumero(Txt_numero.getText());
            cliente_tela.setcomplemento(Txt_complemento.getText());
            cliente_tela.setbairro(Txt_bairro.getText());
            cliente_tela.setcidade(Txt_cidade.getText());
            cliente_tela.setuf(Txt_uf.getText());
            
                 

            
            objcon.alteraRegistroJFBD("Clientes", cliente_tela.alteraDadoSQLValues(), "ID_CLI ='" + Txt_id.getText()+"'");
                  
 
          }
          
          
           operacao = "Alterar";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
              cliente_tela = objcon.pesquisaClienteJFBD("CLIENTES","ID_CLI = '" + Txt_id.getText() + "'");
          
        Txt_id.setText(Integer.toString(cliente_tela.getid_cli()));
        Txt_telefone.setText(cliente_tela.gettelefone());
        Txt_nome.setText(cliente_tela.getnome());
        TxtDataNas.setText(cliente_tela.getdataNascimento());
        Txt_CPF.setText(cliente_tela.getcpf());
        Txt_Cnpj.setText(String.valueOf(cliente_tela.getcnpj()));
        txtcep.setText(cliente_tela.getcep());
        Txt_endereco.setText(cliente_tela.getendereco());
        Txt_numero.setText(cliente_tela.getnumero());
        Txt_complemento.setText(cliente_tela.getcomplemento());
        Txt_bairro.setText(cliente_tela.getbairro());
        Txt_cidade.setText(cliente_tela.getcidade());
        Txt_uf.setText(cliente_tela.getuf());
            
                   
          jLabel14.setVisible(true);
            jLabel10.setVisible(true);
            jLabel1.setVisible(true);
            Jlabel16.setVisible(true);
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
            jlabel20.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel7.setVisible(true);
            jLabel6.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            
            Txt_id.setVisible(true);
            Txt_telefone.setVisible(true);
            Txt_nome.setVisible(true);
            TxtDataNas.setVisible(true);
            Txt_CPF.setVisible(true);
            Txt_Cnpj.setVisible(true);
            txtcep.setVisible(true);
            Txt_endereco.setVisible(true);
            Txt_numero.setVisible(true);
            Txt_complemento.setVisible(true);
            Txt_bairro.setVisible(true);
            Txt_cidade.setVisible(true);
            Txt_uf.setVisible(true);
            Btn_Cadastrar.setText("Alterar");
            Btn_Ler.setVisible(false);
            Btn_limparTela.setVisible(false);
            operacaoAtivaGlobal = "Alteração";
           
                     
          }
          
          operacao = "Exclusão";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
              objcon.excluiRegistroJFBD("Clientes","ID_CLI ="+Txt_id.getText());
                  
        Txt_id.setText("");
        Txt_telefone.setText(" ");
        Txt_nome.setText("");
        TxtDataNas.setText("");
        Txt_CPF.setText("");
        Txt_Cnpj.setText("");
        txtcep.setText("");
        Txt_endereco.setText("");
        Txt_numero.setText("");
        Txt_complemento.setText("");
        Txt_bairro.setText("");
        Txt_cidade.setText("");
        Txt_uf.setText("");
        this.dispose();
 
          }
          
          operacao = "Excluir";
          if (operacaoAtivaGlobal.equals(operacao))
          {
              connectDAO objcon = new connectDAO();
              cliente_tela = objcon.pesquisaClienteJFBD("CLIENTES","ID_CLI = '" + Txt_id.getText() + "'");
          
        Txt_id.setText(Integer.toString(cliente_tela.getid_cli()));
        Txt_telefone.setText(cliente_tela.gettelefone());
        Txt_nome.setText(cliente_tela.getnome());
        TxtDataNas.setText(cliente_tela.getdataNascimento());
        Txt_CPF.setText(cliente_tela.getcpf());
        Txt_Cnpj.setText(String.valueOf(cliente_tela.getcnpj()));
        txtcep.setText(cliente_tela.getcep());
        Txt_endereco.setText(cliente_tela.getendereco());
        Txt_numero.setText(cliente_tela.getnumero());
        Txt_complemento.setText(cliente_tela.getcomplemento());
        Txt_bairro.setText(cliente_tela.getbairro());
        Txt_cidade.setText(cliente_tela.getcidade());
        Txt_uf.setText(cliente_tela.getuf());
            
          
          
          jLabel14.setVisible(true);
            jLabel10.setVisible(true);
            jLabel1.setVisible(true);
            Jlabel16.setVisible(true);
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
            jlabel20.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel7.setVisible(true);
            jLabel6.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            
            
            Txt_id.setVisible(true);
            Txt_telefone.setVisible(true);
            Txt_nome.setVisible(true);
            TxtDataNas.setVisible(true);
            Txt_CPF.setVisible(true);
            Txt_Cnpj.setVisible(true);
            txtcep.setVisible(true);
            Txt_endereco.setVisible(true);
            Txt_numero.setVisible(true);
            Txt_complemento.setVisible(true);
            Txt_bairro.setVisible(true);
            Txt_cidade.setVisible(true);
            Txt_uf.setVisible(true);
                                   
            Txt_id.setEditable(false);
            Txt_telefone.setEditable(false);
            Txt_nome.setEditable(false);
            TxtDataNas.setEditable(false);
            Txt_CPF.setEditable(false);
            Txt_Cnpj.setEditable(false);
            txtcep.setEditable(false);
            Txt_endereco.setEditable(false);
            Txt_numero.setEditable(false);
            Txt_complemento.setEditable(false);
            Txt_bairro.setEditable(false);
            Txt_cidade.setEditable(false);
            Txt_uf.setEditable(false);
            Btn_Cadastrar.setText("Excluir");
            Btn_Ler.setVisible(false);
            Btn_limparTela.setVisible(false);
            operacaoAtivaGlobal = "Exclusão";
          
          }
          
    }//GEN-LAST:event_Btn_CadastrarActionPerformed

          
          
          
    private void Txt_complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_complementoActionPerformed

    private void Txt_ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ufActionPerformed

    private void Txt_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_cidadeActionPerformed

    private void Txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_telefoneActionPerformed

    private void Txt_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_bairroActionPerformed

    private void Btn_limparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limparTelaActionPerformed
        // TODO add your handling code here:
        Txt_id.setText("");
        Txt_telefone.setText(" ");
        Txt_nome.setText("");
        TxtDataNas.setText("");
        Txt_CPF.setText("");
        Txt_Cnpj.setText("");
        txtcep.setText("");
        Txt_endereco.setText("");
        Txt_numero.setText("");
        Txt_complemento.setText("");
        Txt_bairro.setText("");
        Txt_cidade.setText("");
        Txt_uf.setText("");
    }//GEN-LAST:event_Btn_limparTelaActionPerformed

    private void Btn_LerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LerActionPerformed
        // TODO add your handling code here:
        Txt_id.setText(Integer.toString(cliente_tela.getid_cli()));
        Txt_telefone.setText(cliente_tela.gettelefone());
        Txt_nome.setText(cliente_tela.getnome());
        TxtDataNas.setText(cliente_tela.getdataNascimento());
        Txt_CPF.setText(cliente_tela.getcpf());
        Txt_Cnpj.setText(String.valueOf(cliente_tela.getcnpj()));
        txtcep.setText(cliente_tela.getcep());
        Txt_endereco.setText(cliente_tela.getendereco());
        Txt_numero.setText(cliente_tela.getnumero());
        Txt_complemento.setText(cliente_tela.getcomplemento());
        Txt_bairro.setText(cliente_tela.getbairro());
        Txt_cidade.setText(cliente_tela.getcidade());
        Txt_uf.setText(cliente_tela.getuf());
        
    }//GEN-LAST:event_Btn_LerActionPerformed

    private void Txt_CnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CnpjActionPerformed

    private void Txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_idActionPerformed

    private void txtcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcepActionPerformed

    private void TxtDataNasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDataNasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDataNasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and displayTxt_email */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cadastrar;
    private javax.swing.JButton Btn_Ler;
    private javax.swing.JButton Btn_limparTela;
    private javax.swing.JLabel Jlabel16;
    private javax.swing.JTextField TxtDataNas;
    private javax.swing.JTextField Txt_CPF;
    private javax.swing.JTextField Txt_Cnpj;
    private javax.swing.JTextField Txt_bairro;
    private javax.swing.JTextField Txt_cidade;
    private javax.swing.JTextField Txt_complemento;
    private javax.swing.JTextField Txt_endereco;
    private javax.swing.JTextField Txt_id;
    private javax.swing.JTextField Txt_nome;
    private javax.swing.JTextField Txt_numero;
    private javax.swing.JTextField Txt_telefone;
    private javax.swing.JTextField Txt_uf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabel20;
    private javax.swing.JTextField txtcep;
    // End of variables declaration//GEN-END:variables
}
